language: node_js
node_js:
  - 0.1
install: "./tasks/pre-test.sh"
after_success: "./tasks/post-test.sh && ./tasks/dist.sh && cd dist"
deploy:
  - provider: appfog
    email: jamesseanwright@gmail.com
    app: jameswright
    password:
      secure: CMTuF11s27GOLdNBFnFv3fAaymiY9Klx2oPrr3mC/gqV47myVvqvEPFidgmBkHjP/kRMMES8H0n4TquSxJ8aprgZpOlad9KW9HUJH745L2AA4rUSMZ68piEMK39Mu+iQFUTlUaRzFFSD8iDtwzvBGalkon+ZA8TtJp1UHlwePZo=
    on:
      branch: development
    skip_cleanup: true
  - provider: appfog
    email: jamesseanwright@gmail.com
    app: jameswright
    password:
      secure: CMTuF11s27GOLdNBFnFv3fAaymiY9Klx2oPrr3mC/gqV47myVvqvEPFidgmBkHjP/kRMMES8H0n4TquSxJ8aprgZpOlad9KW9HUJH745L2AA4rUSMZ68piEMK39Mu+iQFUTlUaRzFFSD8iDtwzvBGalkon+ZA8TtJp1UHlwePZo=
    on:
      branch: development
    skip_cleanup: true
  - provider: heroku
    app: james-wright-beta
    strategy: git
    api_key:
      secure: jgJRdshxNSuIBNtdqcy5HbzdcRoljHSgMO0/oqsEiL/hl3DFoIp7tIOwCKnWUg/ciZF34eAxfYpjfqHDDltwyNbyaIXckjLNzXBSTNj6JMFfF+mTJ4Mk8DNziPD7a0Sd2vvQ0JLC13gFH3jPdiIcsjHN4G+IZRC6xSrwx46jiH4=
    on:
      branch: staging
    skip_cleanup: true
  - provider: heroku
    app: james-wright-prod
    strategy: git
    api_key:
      secure: jgJRdshxNSuIBNtdqcy5HbzdcRoljHSgMO0/oqsEiL/hl3DFoIp7tIOwCKnWUg/ciZF34eAxfYpjfqHDDltwyNbyaIXckjLNzXBSTNj6JMFfF+mTJ4Mk8DNziPD7a0Sd2vvQ0JLC13gFH3jPdiIcsjHN4G+IZRC6xSrwx46jiH4=
    on:
      branch: master
    skip_cleanup: true